version: 0.2

phases:
  install:
    commands:
      # install node 16
      - echo Installing node 16...
      - curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
      - sudo yum install -y nodejs
      # install yarn
      - echo Installing Yarn...
      - curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo
      - sudo yum install yarn
  pre_build:
    commands:
      #install dependencies
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      # build
      - echo Building...
      - yarn build
artifacts:
  files:
    - "**/*"
  discart-paths: no
  base-directory: build